### ISSUE TITLE
"About" says no API calls, but `rates` makes an API call

### ISSUE THREAD

**Issue by edfletcher** [nzldev/uni-convert-currency#1]
About text: "currency converter library **that doesn't require subscribing to any API calls.**"

[index.js line 225](https://github.com/nzldev/uni-convert-currency/blob/main/index.js#L225): 
```
return got(`https://www.google.co.in/search?q=${this.currencyAmount}+${this.currencyFrom}+to+${this.currencyTo}`)
```

The whole point of using a library like this for many consumers would be that it doesn't make external network calls, and your "About" misleads about that, requiring developers to find out the hard way.

😕

**Comment by nzldev** [comment]
this api not subscribing payment required

**Comment by nzldev** [comment]
> About text: "currency converter library **that doesn't require subscribing to any API calls.**"
> 
> [index.js line 225](https://github.com/nzldev/uni-convert-currency/blob/main/index.js#L225):
> 
> ```
> return got(`https://www.google.co.in/search?q=${this.currencyAmount}+${this.currencyFrom}+to+${this.currencyTo}`)
> ```
> 
> The whole point of using a library like this for many consumers would be that it doesn't make external network calls, and your "About" misleads about that, requiring developers to find out the hard way.
> 
> 😕


this api not subscribing payment required

**Comment by edfletcher** [comment]
> this api not subscribing payment required

That's inconsequential. When you say "subscribing to API calls" I read "it doesn't make API calls", not that it doesn't cost money: "subscribing" has a connotation in programming that a consumer just opens an eternal listening connection. Many people will make the same assumption I did.

**Comment by nzldev** [comment]
> not subscribing payment required

okay bro i will change my description.
thanks for your suggestion

**Comment by nzldev** [comment]
> > this api not subscribing payment required
> 
> That's inconsequential. When you say "subscribing to API calls" I read "it doesn't make API calls", not that it doesn't cost money: "subscribing" has a connotation in programming that a consumer just opens an eternal listening connection. Many people will make the same assumption I did.

okay bro i will change my description.
thanks for your suggestion

**Comment by edfletcher** [comment]
Thank you! 🙌
